const mysql = require('mysql2/promise');
const fs = require('fs');

async function init() {
  console.log("Connecting...");
  try {
    const connection = await mysql.createConnection('mysql://root:zhpURYQhBGrZHghDAbvoUGGliDEiyabk@metro.proxy.rlwy.net:19488/railway');

    console.log("Connected to Railway MySQL!");
    
    // Hardcoded problems list from seed.js
    const problems = [
      { chapter: 1, round: 1, difficulty: 'easy', language: 'python', points: 10, title: 'Add Two Numbers', description: 'Fix the bugs so the program correctly adds two numbers entered by the user.', buggy_code: 'def add(a, b)\n    result = a - b\n    return result\n\nx = input("Enter first number:")\ny = input("Enter second number:")\n\nprint("Sum is:", add(x, y))', hint: 'Function definition syntax error; Wrong arithmetic operator; Input datatype issue', expected_output: 'Enter first number: 5\nEnter second number: 3\nSum is: 8' },
      { chapter: 1, round: 2, difficulty: 'easy', language: 'python', points: 10, title: 'Print Numbers from 1 to N', description: 'Fix the code so it prints numbers from 1 to N.', buggy_code: 'def print_numbers(n):\n    for i in range(1,n)\n    print(i)\n\nnum = input("Enter number:")\nprint_numbers(num)', hint: 'Missing colon in loop; Input datatype issue; Range should include final number', expected_output: 'Enter number: 5\n1\n2\n3\n4\n5' },
      { chapter: 1, round: 1, difficulty: 'easy', language: 'java', points: 10, title: 'Multiply Two Numbers', description: 'Fix the code so it multiplies two numbers.', buggy_code: 'public class Main {\n    public static void main(String args[]) {\n        int a = 5\n        int b = 4;\n        int result = a + b;\n\n        System.out.println("Result: " + result)\n    }\n}', hint: 'Missing semicolon; Wrong arithmetic operator; Print statement syntax', expected_output: 'Result: 20' },
      { chapter: 1, round: 2, difficulty: 'easy', language: 'java', points: 10, title: 'Print Hello 5 Times', description: 'Fix the program so it prints Hello five times.', buggy_code: 'public class Main {\n    public static void main(String[] args) {\n        for(int i=1; i<=5; i--) {\n            System.out.println("Hello")\n        }\n    }\n}', hint: 'Wrong loop increment; Missing semicolon; Infinite loop risk', expected_output: 'Hello\nHello\nHello\nHello\nHello' },
      { chapter: 1, round: 1, difficulty: 'easy', language: 'c', points: 10, title: 'Square of a Number', description: 'Fix the program to print the square of a number.', buggy_code: '#include <stdio.h>\n\nint main() {\n    int n = 5\n    int square = n ^ 2;\n\n    printf("Square: %d", square)\n}', hint: 'Missing semicolon; Wrong operator for square; Missing return statement', expected_output: 'Square: 25' },
      { chapter: 1, round: 2, difficulty: 'easy', language: 'c', points: 10, title: 'Sum of Two Numbers', description: 'Fix the program to correctly compute the sum.', buggy_code: '#include <stdio.h>\n\nint main() {\n    int a = 10;\n    int b = 20;\n    int sum;\n\n    sum = a - b\n\n    printf("Sum = %d\\n", sum);\n}', hint: 'Wrong arithmetic operator; Missing semicolon; Logic issue', expected_output: 'Sum = 30' },
      { chapter: 2, round: 1, difficulty: 'medium', language: 'python', points: 15, title: 'Factorial Calculation', description: 'Fix the bugs so the program correctly computes the factorial of 5.', buggy_code: 'def factorial(n):\n    fact = 0\n    for i in range(1, n):\n        fact = fact * i\n    return fact\n\nprint(factorial(5))', hint: 'Initial value incorrect; Range should include n; Multiplication logic issue', expected_output: '120' },
      { chapter: 2, round: 2, difficulty: 'medium', language: 'python', points: 20, title: 'Print Even Numbers', description: 'Fix the code so it prints all even numbers from 2 to 10.', buggy_code: 'def print_even(n):\n    for i in range(n):\n        if i % 2 = 0:\n            print(i)\n\nprint_even("10")', hint: 'Comparison operator error; Datatype issue; Range start problem', expected_output: '2\n4\n6\n8\n10' },
      { chapter: 2, round: 1, difficulty: 'medium', language: 'java', points: 20, title: 'Reverse a Number', description: 'Fix the code so it reverses the digits of 123 to produce 321.', buggy_code: 'public class Main {\n    public static void main(String[] args) {\n        int num = 123;\n        int rev = 0;\n\n        while(num > 0) {\n            int rem = num % 10\n            rev = rev + rem;\n            num = num / 10;\n        }\n\n        System.out.println(rev);\n    }\n}', hint: 'Missing semicolon; Reverse logic incorrect; Multiplication missing', expected_output: '321' },
      { chapter: 2, round: 2, difficulty: 'medium', language: 'java', points: 20, title: 'Sum of Array', description: 'Fix the code so it computes the sum of the array elements correctly.', buggy_code: 'public class Main {\n    public static void main(String[] args) {\n        int arr[] = {1,2,3,4,5};\n        int sum = 0;\n\n        for(int i=0;i<=arr.length;i++){\n            sum = sum + arr[i];\n        }\n\n        System.out.println("Sum = " + sum)\n    }\n}', hint: 'Array index limit issue; Loop condition error; Missing semicolon', expected_output: 'Sum = 15' },
      { chapter: 2, round: 1, difficulty: 'medium', language: 'c', points: 20, title: 'Largest of Three Numbers', description: 'Fix the program so it correctly identifies the largest of three numbers.', buggy_code: '#include<stdio.h>\n\nint main() {\n    int a = 5, b = 8, c = 3;\n    int largest;\n\n    if(a>b && a>c)\n        largest = b;\n    else if(b>a && b>c)\n        largest = c;\n    else\n        largest = a;\n\n    printf("%d",largest);\n}', hint: 'Logic error in assignments; Wrong values assigned; Condition issue', expected_output: '8' },
      { chapter: 2, round: 2, difficulty: 'medium', language: 'c', points: 20, title: 'Count Digits', description: 'Fix the program so it correctly counts the number of digits in 12345.', buggy_code: '#include<stdio.h>\n\nint main() {\n    int n = 12345;\n    int count = 1;\n\n    while(n > 0)\n    {\n        count++;\n        n = n/10;\n    }\n\n    printf("Digits = %d",count);\n}', hint: 'Initial value incorrect; Off-by-one error; Loop logic issue', expected_output: 'Digits = 5' },
      { chapter: 3, round: 1, difficulty: 'hard', language: 'python', points: 25, title: 'Prime Number Check', description: 'Fix the bugs so the program correctly checks whether an input number is prime.', buggy_code: 'def is_prime(n)\n    if n <= 1:\n        return True\n\n    for i in range(2,n):\n        if n % i == 0\n            return False\n        else:\n            return True\n\nnum = input("Enter number:")\nif is_prime(num):\n    print("Prime")\nelse\n    print("Not Prime")', hint: 'Missing colon; Input datatype issue; Loop logic incorrect; Prime condition wrong; Syntax error in else', expected_output: 'Enter number: 7\nPrime' },
      { chapter: 3, round: 2, difficulty: 'hard', language: 'python', points: 30, title: 'Sum of List', description: 'Fix the bugs so the program correctly sums a list of numbers and prints the total.', buggy_code: 'numbers = [1,2,3,4,5]\ntotal = 0\n\nfor i in range(len(numbers)+1):\n    total = numbers[i]\n\nprint("Total:", total)', hint: 'Index overflow; Accumulation logic wrong; Variable name mismatch; Range issue; Avoid overwriting built-in sum', expected_output: 'Total: 15' },
      { chapter: 3, round: 1, difficulty: 'hard', language: 'java', points: 30, title: 'Fibonacci Series', description: 'Fix the bugs so the program prints the first 7 Fibonacci numbers.', buggy_code: 'public class Main {\n    public static void main(String[] args) {\n\n        int n = 7\n        int a = 0, b = 1;\n\n        for(int i=0;i<n;i++);\n        {\n            int c = a + b;\n            System.out.println(c)\n            a = b;\n            b = c;\n        }\n    }\n}', hint: 'Missing semicolon; Extra semicolon in loop; Print statement syntax; Fibonacci logic error; Loop issue', expected_output: '1\n1\n2\n3\n5\n8\n13' },
      { chapter: 3, round: 2, difficulty: 'hard', language: 'java', points: 30, title: 'Maximum in Array', description: 'Fix the bugs so the program correctly finds the maximum value in an array.', buggy_code: 'public class Main {\n    public static void main(String[] args) {\n\n        int arr[] = {2,9,4,7,5};\n        int max = 0;\n\n        for(int i=1;i<arr.length;i++)\n        {\n            if(arr[i] < max)\n                max = arr[i]\n        }\n\n        System.out.println("Max = " + max);\n    }\n}', hint: 'Initial value problem; Comparison operator wrong; Missing semicolon; Loop logic issue; Incorrect max logic', expected_output: 'Max = 9' },
      { chapter: 3, round: 1, difficulty: 'hard', language: 'c', points: 30, title: 'Reverse Number', description: 'Fix the bugs so the program correctly reverses the digits of 1234.', buggy_code: '#include<stdio.h>\n\nint main() {\n\n    int n = 1234\n    int rev;\n\n    while(n > 0)\n    {\n        int rem = n % 10;\n        rev = rev * 10 + rem;\n        n / 10;\n    }\n\n    printf("Reverse = %d", rev);\n\n}', hint: 'Missing semicolon; Uninitialized variable; Division assignment missing; Reverse logic; Missing return statement', expected_output: 'Reverse = 4321' },
      { chapter: 3, round: 2, difficulty: 'hard', language: 'c', points: 30, title: 'Sum of Array', description: 'Fix the bugs so the program correctly sums all elements of the array.', buggy_code: '#include<stdio.h>\n\nint main() {\n\n    int arr[5] = {1,2,3,4,5};\n    int sum;\n\n    for(int i=0;i<=5;i++)\n    {\n        sum = arr[i];\n    }\n\n    printf("Sum = %d", sum)\n\n}', hint: 'Sum not initialized; Array index overflow; Accumulation logic wrong; Loop condition error; Missing semicolon', expected_output: 'Sum = 15' }
    ];

    await connection.execute('SET FOREIGN_KEY_CHECKS = 0');
    await connection.execute('TRUNCATE TABLE problems');
    await connection.execute('SET FOREIGN_KEY_CHECKS = 1');

    for (const p of problems) {
      await connection.execute(
        `INSERT INTO problems (chapter, round, difficulty, language, title, description, buggy_code, expected_output, points, hint)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [p.chapter, p.round, p.difficulty, p.language, p.title, p.description, p.buggy_code, p.expected_output, p.points, p.hint]
      );
    }
    
    console.log(`✅ ${problems.length} problems pushed to Railway.`);
    await connection.end();
  } catch (err) {
    console.error("Connection failed:", err);
  }
}

init();
